apiVersion: v1
kind: ConfigMap
metadata:
  name: rdas-config
  namespace: rdas
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
  CACHE_TTL_COUNTRIES: "86400"
  CACHE_TTL_CURRENCIES: "86400"
  CACHE_TTL_CONTINENTS: "604800"
  CACHE_TTL_LANGUAGES: "86400"
